// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQDbcHoU_tZQ8e_plBu1eF1s-YGJNLzFY',
    appId: '1:462074755015:web:4b89e0ee883e3457af0be2',
    messagingSenderId: '462074755015',
    projectId: 'flipflow-b312122',
    authDomain: 'flipflow-b312122.firebaseapp.com',
    storageBucket: 'flipflow-b312122.firebasestorage.app',
    measurementId: 'G-6E0C28C97Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKnTYAjTseW-KOVs3LaqbUfnrXA98w0hg',
    appId: '1:462074755015:android:f9152ccdb725f7fbaf0be2',
    messagingSenderId: '462074755015',
    projectId: 'flipflow-b312122',
    storageBucket: 'flipflow-b312122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIZslUvR_O3jjLVI1Op8Wierza8CeXU-w',
    appId: '1:462074755015:ios:18f6a45d4f781aa4af0be2',
    messagingSenderId: '462074755015',
    projectId: 'flipflow-b312122',
    storageBucket: 'flipflow-b312122.firebasestorage.app',
    iosBundleId: 'com.cescu.flipflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIZslUvR_O3jjLVI1Op8Wierza8CeXU-w',
    appId: '1:462074755015:ios:18f6a45d4f781aa4af0be2',
    messagingSenderId: '462074755015',
    projectId: 'flipflow-b312122',
    storageBucket: 'flipflow-b312122.firebasestorage.app',
    iosBundleId: 'com.cescu.flipflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQDbcHoU_tZQ8e_plBu1eF1s-YGJNLzFY',
    appId: '1:462074755015:web:dca258fb0b39ff9caf0be2',
    messagingSenderId: '462074755015',
    projectId: 'flipflow-b312122',
    authDomain: 'flipflow-b312122.firebaseapp.com',
    storageBucket: 'flipflow-b312122.firebasestorage.app',
    measurementId: 'G-B77QMHP8CG',
  );
}
